import PDFDocument from "pdfkit";

// ============================================================
// CONSTANTS
// ============================================================

const BRAND_COLOR = "#0891b2";
const TEXT_COLOR = "#111827";
const MUTED_COLOR = "#6b7280";
const BORDER_COLOR = "#d1d5db";

const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;

const DEFAULT_MARGIN = 50;

// ============================================================
// HELPERS
// ============================================================

const formatDate = (date) => {
  if (!date) {
    return "N/A";
  }

  const parsedDate = new Date(date);

  if (Number.isNaN(parsedDate.getTime())) {
    return "N/A";
  }

  return parsedDate.toLocaleDateString();
};

const formatDateTime = (date) => {
  if (!date) {
    return "N/A";
  }

  const parsedDate = new Date(date);

  if (Number.isNaN(parsedDate.getTime())) {
    return "N/A";
  }

  return parsedDate.toLocaleString();
};

const formatAmount = (
  amount = 0,
  currency = "USD"
) => {
  const numericAmount = Number(amount) || 0;

  return `${currency} ${numericAmount.toLocaleString(
    undefined,
    {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }
  )}`;
};

const safeText = (value, fallback = "N/A") => {
  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return fallback;
  }

  return String(value);
};

// ============================================================
// PDF BUFFER HELPER
// ============================================================

const documentToBuffer = (doc) => {
  return new Promise((resolve, reject) => {
    const chunks = [];

    doc.on("data", (chunk) => {
      chunks.push(chunk);
    });

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);
  });
};

// ============================================================
// HEADER
// ============================================================

const addHeader = (
  doc,
  title,
  subtitle = null
) => {
  doc
    .fontSize(24)
    .fillColor(BRAND_COLOR)
    .text("SkillSync", {
      align: "center",
    });

  doc
    .fontSize(18)
    .fillColor(TEXT_COLOR)
    .text(title, {
      align: "center",
    });

  if (subtitle) {
    doc
      .fontSize(10)
      .fillColor(MUTED_COLOR)
      .text(subtitle, {
        align: "center",
      });
  }

  doc.moveDown();
};

// ============================================================
// SECTION TITLE
// ============================================================

const addSectionTitle = (
  doc,
  title
) => {
  doc
    .fontSize(14)
    .fillColor(BRAND_COLOR)
    .text(title.toUpperCase(), {
      underline: true,
    });

  doc.moveDown(0.5);

  doc
    .fontSize(11)
    .fillColor(TEXT_COLOR);
};

// ============================================================
// FOOTER
// ============================================================

const addFooter = (doc) => {
  const previousY = doc.y;

  doc
    .fontSize(9)
    .fillColor(MUTED_COLOR)
    .text(
      "Generated by SkillSync",
      DEFAULT_MARGIN,
      PAGE_HEIGHT - 45,
      {
        width:
          PAGE_WIDTH -
          DEFAULT_MARGIN * 2,
        align: "center",
      }
    );

  doc.y = previousY;
};

// ============================================================
// PAGE NUMBERS
// ============================================================

const addPageNumbers = (doc) => {
  const range =
    doc.bufferedPageRange();

  for (
    let i = range.start;
    i < range.start + range.count;
    i++
  ) {
    doc.switchToPage(i);

    doc
      .fontSize(8)
      .fillColor(MUTED_COLOR)
      .text(
        `Page ${
          i + 1
        } of ${
          range.count
        }`,
        DEFAULT_MARGIN,
        PAGE_HEIGHT - 30,
        {
          width:
            PAGE_WIDTH -
            DEFAULT_MARGIN * 2,
          align: "center",
        }
      );
  }
};

// ============================================================
// APPLICATIONS REPORT
// ============================================================

export const generateApplicationsPDF = (
  applications,
  res
) => {
  if (!Array.isArray(applications)) {
    throw new Error(
      "Applications must be an array"
    );
  }

  const doc = new PDFDocument({
    size: "A4",
    margin: DEFAULT_MARGIN,
    bufferPages: true,
  });

  res.setHeader(
    "Content-Type",
    "application/pdf"
  );

  res.setHeader(
    "Content-Disposition",
    "attachment; filename=applications-report.pdf"
  );

  doc.pipe(res);

  addHeader(
    doc,
    "Applications Report",
    `Generated: ${formatDateTime(new Date())}`
  );

  // ==========================================================
  // SUMMARY
  // ==========================================================

  const pending =
    applications.filter(
      (application) =>
        application.status === "pending"
    ).length;

  const accepted =
    applications.filter(
      (application) =>
        application.status === "accepted"
    ).length;

  const rejected =
    applications.filter(
      (application) =>
        application.status === "rejected"
    ).length;

  addSectionTitle(
    doc,
    "Summary"
  );

  doc.text(
    `Total Applications: ${applications.length}`
  );

  doc.text(
    `Accepted: ${accepted}`
  );

  doc.text(
    `Pending: ${pending}`
  );

  doc.text(
    `Rejected: ${rejected}`
  );

  doc.moveDown(2);

  // ==========================================================
  // TABLE
  // ==========================================================

  const tableX = DEFAULT_MARGIN;
  const tableWidth = 495;
  const headerHeight = 25;

  let y = doc.y;

  doc
    .rect(
      tableX,
      y,
      tableWidth,
      headerHeight
    )
    .fill(BRAND_COLOR);

  doc
    .fontSize(10)
    .fillColor("white")
    .text(
      "Developer",
      tableX + 10,
      y + 7,
      { width: 110 }
    );

  doc.text(
    "Job",
    tableX + 125,
    y + 7,
    { width: 150 }
  );

  doc.text(
    "Status",
    tableX + 280,
    y + 7,
    { width: 80 }
  );

  doc.text(
    "Date",
    tableX + 390,
    y + 7,
    { width: 90 }
  );

  y += 35;

  // ==========================================================
  // ROWS
  // ==========================================================

  applications.forEach(
    (application, index) => {
      if (y > 740) {
        doc.addPage();

        y = DEFAULT_MARGIN;

        doc
          .fontSize(10)
          .fillColor(TEXT_COLOR);

        // Repeat table header
        doc
          .rect(
            tableX,
            y,
            tableWidth,
            headerHeight
          )
          .fill(BRAND_COLOR);

        doc
          .fontSize(10)
          .fillColor("white")
          .text(
            "Developer",
            tableX + 10,
            y + 7,
            { width: 110 }
          );

        doc.text(
          "Job",
          tableX + 125,
          y + 7,
          { width: 150 }
        );

        doc.text(
          "Status",
          tableX + 280,
          y + 7,
          { width: 80 }
        );

        doc.text(
          "Date",
          tableX + 390,
          y + 7,
          { width: 90 }
        );

        y += 35;
      }

      const developerName =
        application.developer?.username ||
        application.developer?.name ||
        "N/A";

      const jobTitle =
        application.job?.title ||
        "N/A";

      const status =
        application.status || "N/A";

      const date =
        formatDate(
          application.createdAt
        );

      // Alternating row background
      if (index % 2 === 0) {
        doc
          .rect(
            tableX,
            y - 5,
            tableWidth,
            25
          )
          .fill("#f9fafb");
      }

      doc
        .fontSize(9)
        .fillColor(TEXT_COLOR)
        .text(
          developerName,
          tableX + 10,
          y,
          { width: 110 }
        );

      doc.text(
        jobTitle,
        tableX + 125,
        y,
        { width: 150 }
      );

      doc.text(
        status,
        tableX + 280,
        y,
        { width: 80 }
      );

      doc.text(
        date,
        tableX + 390,
        y,
        { width: 90 }
      );

      y += 25;
    }
  );

  addPageNumbers(doc);

  doc.end();
};

// ============================================================
// GENERATE CONTRACT PDF
// ============================================================

export const generatePDFContract =
  async (contract) => {
    if (!contract) {
      throw new Error(
        "Contract is required"
      );
    }

    const doc = new PDFDocument({
      size: "A4",
      margin: DEFAULT_MARGIN,
      bufferPages: true,
    });

    // ==========================================================
    // HEADER
    // ==========================================================

    addHeader(
      doc,
      "Freelance Contract",
      `Contract ID: ${safeText(
        contract._id
      )} • Date: ${formatDate(
        contract.createdAt ||
          new Date()
      )}`
    );

    // ==========================================================
    // PARTIES
    // ==========================================================

    addSectionTitle(
      doc,
      "Parties"
    );

    const clientName =
      contract.client?.username ||
      contract.client?.name ||
      "N/A";

    const clientEmail =
      contract.client?.email ||
      "N/A";

    const developerName =
      contract.developer?.username ||
      contract.developer?.name ||
      "N/A";

    const developerEmail =
      contract.developer?.email ||
      "N/A";

    doc.text(
      `Client: ${clientName}`
    );

    doc.text(
      `Client Email: ${clientEmail}`
    );

    doc.moveDown(0.5);

    doc.text(
      `Developer: ${developerName}`
    );

    doc.text(
      `Developer Email: ${developerEmail}`
    );

    doc.moveDown(2);

    // ==========================================================
    // PROJECT DETAILS
    // ==========================================================

    addSectionTitle(
      doc,
      "Project Details"
    );

    const jobTitle =
      contract.job?.title ||
      "N/A";

    const jobDescription =
      contract.job?.description ||
      "N/A";

    doc.text(
      `Job Title: ${jobTitle}`
    );

    doc.moveDown(0.5);

    doc.text(
      `Description: ${jobDescription}`,
      {
        width: 495,
        lineGap: 3,
      }
    );

    doc.moveDown(2);

    // ==========================================================
    // PAYMENT TERMS
    // ==========================================================

    addSectionTitle(
      doc,
      "Payment Terms"
    );

    const currency =
      contract.currency ||
      contract.job?.currency ||
      "USD";

    const amount =
      contract.amount || 0;

    const platformFee =
      contract.commission ??
      contract.platformFee ??
      0;

    const developerAmount =
      contract.developerAmount ??
      amount;

    doc.text(
      `Project Amount: ${formatAmount(
        amount,
        currency
      )}`
    );

    doc.text(
      `Platform Fee: ${formatAmount(
        platformFee,
        currency
      )}`
    );

    doc.text(
      `Developer Receives: ${formatAmount(
        developerAmount,
        currency
      )}`
    );

    doc.moveDown(2);

    // ==========================================================
    // TERMS
    // ==========================================================

    addSectionTitle(
      doc,
      "Terms & Conditions"
    );

    const terms =
      contract.terms ||
      "Standard SkillSync terms and conditions apply.";

    doc.text(terms, {
      width: 495,
      lineGap: 4,
    });

    doc.moveDown(2);

    // ==========================================================
    // SIGNATURES
    // ==========================================================

    addSectionTitle(
      doc,
      "Signatures"
    );

    const clientSigned =
      contract.clientSigned
        ? "Signed"
        : "Pending";

    const developerSigned =
      contract.developerSigned
        ? "Signed"
        : "Pending";

    const clientDate =
      contract.clientSignedAt
        ? formatDate(
            contract.clientSignedAt
          )
        : "___/___/____";

    const developerDate =
      contract.developerSignedAt
        ? formatDate(
            contract.developerSignedAt
          )
        : "___/___/____";

    doc.text(
      `Client: ${clientSigned}`
    );

    doc.text(
      `Date: ${clientDate}`
    );

    doc.moveDown();

    doc.text(
      `Developer: ${developerSigned}`
    );

    doc.text(
      `Date: ${developerDate}`
    );

    doc.moveDown(3);

    doc
      .fontSize(9)
      .fillColor(MUTED_COLOR)
      .text(
        "This document was generated electronically by SkillSync."
      );

    addPageNumbers(doc);

    doc.end();

    return documentToBuffer(doc);
  };

// SAVE CONTRACT PDF
export const saveContractPDF =
  async (contract) => {
    try {
      const pdfBuffer =
        await generatePDFContract(
          contract
        );

      return {
        buffer: pdfBuffer,

        base64:
          pdfBuffer.toString("base64"),

        filename: `contract-${contract._id}.pdf`,

        contentType:
          "application/pdf",
      };
    } catch (error) {
      console.error(
        "Generate contract PDF error:",
        error
      );

      throw new Error(
        "Failed to generate contract PDF"
      );
    }
  };
