import PDFDocument from "pdfkit";

export const generateApplicationsPDF = (applications, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=applications-report.pdf"
  );

  doc.pipe(res);

  // =============================
  // HEADER
  // =============================

  doc
    .fontSize(24)
    .fillColor("#0891b2")
    .text("SkillSync", {
      align: "center",
    });

  doc
    .fontSize(18)
    .fillColor("black")
    .text("Applications Report", {
      align: "center",
    });

  doc.moveDown();

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(`Generated: ${new Date().toLocaleString()}`);

  doc.moveDown();

  // =============================
  // SUMMARY
  // =============================

  const pending = applications.filter(a => a.status === "pending").length;
  const accepted = applications.filter(a => a.status === "accepted").length;
  const rejected = applications.filter(a => a.status === "rejected").length;

  doc.fontSize(13).fillColor("black");

  doc.text(`Total Applications : ${applications.length}`);
  doc.text(`Accepted : ${accepted}`);
  doc.text(`Pending : ${pending}`);
  doc.text(`Rejected : ${rejected}`);

  doc.moveDown(2);

  // =============================
  // TABLE HEADER
  // =============================

  const startY = doc.y;

  doc.rect(50, startY, 500, 25).fill("#0891b2");

  doc
    .fillColor("white")
    .fontSize(11)
    .text("Developer", 60, startY + 7);

  doc.text("Job", 180, startY + 7);

  doc.text("Status", 340, startY + 7);

  doc.text("Date", 450, startY + 7);

  let y = startY + 35;

  // =============================
  // TABLE ROWS
  // =============================

  applications.forEach((application) => {
    if (y > 720) {
      doc.addPage();
      y = 60;
    }

    doc
      .fillColor("black")
      .fontSize(10)
      .text(application.developer.username, 60, y);

    doc.text(application.job.title, 180, y);

    doc.text(application.status, 340, y);

    doc.text(
      new Date(application.createdAt).toLocaleDateString(),
      450,
      y
    );

    y += 25;
  });

  // =============================
  // FOOTER
  // =============================

  doc.moveDown(3);

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by SkillSync © 2026",
      {
        align: "center",
      }
    );

  doc.end();
};