import PDFDocument from "pdfkit";

export const generateApplicationsPDF = (applications, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=applications-report.pdf"
  );

  doc.pipe(res);

  // =============================
  // HEADER
  // =============================

  doc
    .fontSize(24)
    .fillColor("#0891b2")
    .text("SkillSync", {
      align: "center",
    });

  doc
    .fontSize(18)
    .fillColor("black")
    .text("Applications Report", {
      align: "center",
    });

  doc.moveDown();

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(`Generated: ${new Date().toLocaleString()}`);

  doc.moveDown();

  // =============================
  // SUMMARY
  // =============================

  const pending = applications.filter(a => a.status === "pending").length;
  const accepted = applications.filter(a => a.status === "accepted").length;
  const rejected = applications.filter(a => a.status === "rejected").length;

  doc.fontSize(13).fillColor("black");

  doc.text(`Total Applications : ${applications.length}`);
  doc.text(`Accepted : ${accepted}`);
  doc.text(`Pending : ${pending}`);
  doc.text(`Rejected : ${rejected}`);

  doc.moveDown(2);

  // =============================
  // TABLE HEADER
  // =============================

  const startY = doc.y;

  doc.rect(50, startY, 500, 25).fill("#0891b2");

  doc
    .fillColor("white")
    .fontSize(11)
    .text("Developer", 60, startY + 7);

  doc.text("Job", 180, startY + 7);

  doc.text("Status", 340, startY + 7);

  doc.text("Date", 450, startY + 7);

  let y = startY + 35;

  // =============================
  // TABLE ROWS
  // =============================

  applications.forEach((application) => {
    if (y > 720) {
      doc.addPage();
      y = 60;
    }

    doc
      .fillColor("black")
      .fontSize(10)
      .text(application.developer.username, 60, y);

    doc.text(application.job.title, 180, y);

    doc.text(application.status, 340, y);

    doc.text(
      new Date(application.createdAt).toLocaleDateString(),
      450,
      y
    );

    y += 25;
  });

  // =============================
  // FOOTER
  // =============================

  doc.moveDown(3);

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by SkillSync © 2026",
      {
        align: "center",
      }
    );

  doc.end();
};

// Generate Contract PDF
export const generatePDFContract = async (contract) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a buffer to store the PDF
      const chunks = [];
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      // Collect PDF data chunks
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });
      doc.on("error", (err) => reject(err));

      // =============================
      // HEADER
      // =============================
      doc
        .fontSize(24)
        .fillColor("#0891b2")
        .text("SkillSync", {
          align: "center",
        });

      doc
        .fontSize(18)
        .fillColor("black")
        .text("Freelance Contract", {
          align: "center",
        });

      doc.moveDown();

      doc
        .fontSize(10)
        .fillColor("gray")
        .text(`Contract ID: ${contract._id}`, { align: "center" });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: "center" });

      doc.moveDown(2);

      // =============================
      // PARTIES
      // =============================
      doc
        .fontSize(14)
        .fillColor("#0891b2")
        .text("PARTIES", { underline: true });
      doc.moveDown();

      doc.fontSize(11).fillColor("black");

      const clientName = contract.client?.username || "N/A";
      const clientEmail = contract.client?.email || "N/A";
      const developerName = contract.developer?.username || "N/A";
      const developerEmail = contract.developer?.email || "N/A";

      doc.text(`Client: ${clientName} (${clientEmail})`);
      doc.text(`Developer: ${developerName} (${developerEmail})`);

      doc.moveDown(2);

      // =============================
      // PROJECT DETAILS
      // =============================
      doc
        .fontSize(14)
        .fillColor("#0891b2")
        .text("PROJECT DETAILS", { underline: true });
      doc.moveDown();

      doc.fontSize(11).fillColor("black");

      const jobTitle = contract.job?.title || "N/A";
      const jobDescription = contract.job?.description || "N/A";

      doc.text(`Job Title: ${jobTitle}`);
      doc.text(`Description: ${jobDescription}`);

      doc.moveDown(2);

      // =============================
      // PAYMENT TERMS
      // =============================
      doc
        .fontSize(14)
        .fillColor("#0891b2")
        .text("PAYMENT TERMS", { underline: true });
      doc.moveDown();

      doc.fontSize(11).fillColor("black");

      doc.text(`Total Amount: $${contract.amount || 0}`);
      doc.text(`Platform Fee (10%): $${contract.commission || 0}`);
      doc.text(`Developer Receives: $${contract.developerAmount || 0}`);

      doc.moveDown(2);

      // =============================
      // TERMS
      // =============================
      doc
        .fontSize(14)
        .fillColor("#0891b2")
        .text("TERMS & CONDITIONS", { underline: true });
      doc.moveDown();

      doc.fontSize(11).fillColor("black");

      const terms = contract.terms || "Standard terms and conditions apply.";
      doc.text(terms, {
        width: 500,
        align: "left",
      });

      doc.moveDown(2);

      // =============================
      // SIGNATURES
      // =============================
      doc
        .fontSize(14)
        .fillColor("#0891b2")
        .text("SIGNATURES", { underline: true });
      doc.moveDown();

      doc.fontSize(11).fillColor("black");

      // Client signature
      const clientSigned = contract.clientSigned ? "✅ Signed" : "⏳ Pending";
      const clientDate = contract.clientSignedAt
        ? new Date(contract.clientSignedAt).toLocaleDateString()
        : "___/___/____";

      doc.text(`Client: ${clientSigned}`);
      doc.text(`Date: ${clientDate}`);

      doc.moveDown();

      // Developer signature
      const developerSigned = contract.developerSigned ? "✅ Signed" : "⏳ Pending";
      const developerDate = contract.developerSignedAt
        ? new Date(contract.developerSignedAt).toLocaleDateString()
        : "___/___/____";

      doc.text(`Developer: ${developerSigned}`);
      doc.text(`Date: ${developerDate}`);

      doc.moveDown(3);

      // =============================
      // FOOTER
      // =============================
      doc
        .fontSize(10)
        .fillColor("gray")
        .text(
          "Generated by SkillSync © 2026",
          {
            align: "center",
          }
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// ============================================
// Save contract PDF to file
// ============================================
export const saveContractPDF = async (contract) => {
  try {
    const pdfBuffer = await generatePDFContract(contract);
    
    // Create a buffer to store the PDF
    const base64PDF = pdfBuffer.toString('base64');
    
    return {
      buffer: pdfBuffer,
      base64: base64PDF,
    };
  } catch (error) {
    console.error("Save contract PDF error:", error);
    throw new Error("Failed to save contract PDF");
  }
};