import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext();

// Translations
export const translations = {
  en: {
    // Auth
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    username: "Username",
    role: "Role",
    // Jobs
    jobs: "Jobs",
    browseJobs: "Browse Jobs",
    createJob: "Create Job",
    myJobs: "My Jobs",
    jobTitle: "Job Title",
    description: "Description",
    budget: "Budget",
    skills: "Skills",
    // Dashboard
    dashboard: "Dashboard",
    profile: "Profile",
    notifications: "Notifications",
    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    loading: "Loading...",
    noData: "No data found",
    search: "Search",
    filter: "Filter",
    // Applications
    applications: "Applications",
    apply: "Apply",
    coverLetter: "Cover Letter",
    applicants: "Applicants",
    status: "Status",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    clientDashboardSubtitle:
      "Manage your job listings and track developer applications.",
    dashboardStatistics: "Dashboard Statistics",
    quickActions: "Quick Actions",
    loadingDashboard: "Loading dashboard...",
    createJobDesc: "Publish a new job listing.",
    myJobsDesc: "View and manage your posted jobs.",
    profileDesc: "Update your account details.",
    notificationsDesc: "View all your latest notifications.",
    welcomeBack: "Welcome Back",
    welcomeSubtitle: "Enter your credentials to access your account",
    emailAddress: "Email Address",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    signIn: "Sign In",
    signUp: "Sign Up",
    getStarted: "Get Started",
    createAccountSubtitle: "Create an account to join the SkillSync community",
    alreadyHaveAccount: "Already have an account?",
    createNewJob: "Create New Job",
    jobDescription: "Job Description",
    createJobButton: "Create Job",
    jobCreatedSuccessfully: "Job created successfully!",
    failedToCreateJob: "Failed to create job",
    backToJobs: "Back to Jobs",
    client: "Client",
    posted: "Posted",
    requiredSkills: "Required Skills",
    applyForThisJob: "Apply for this Job",
    coverLetterPlaceholder:
      "Explain why you're the right developer for this project...",
    applyNow: "Apply Now",
    submitting: "Submitting...",
    loadingJob: "Loading Job...",
    pleaseWriteCoverLetter: "Please write your cover letter.",
    applicationSubmitted: "Application submitted successfully.",
    applicationFailed: "Application submission failed.",
    myPostedJobs: "My Posted Jobs",
    newest: "Newest",
    highestBudget: "Highest Budget",
    lowestBudget: "Lowest Budget",
    postNewJob: "Post a New Job",
    loadingYourJobs: "Loading your jobs...",
    noJobsPosted: "You haven't posted any jobs yet.",
    viewApplicants: "View Applicants",
    paymentPendingApproval: "Payment pending approval",
    developerPaid: "Developer Paid",
    payDeveloper: "Pay Developer",
    sendSTKPush: "Send STK Push",
    enterMpesaNumber: "Enter the M-Pesa number to send the STK push.",
    cancelButton: "Cancel",
    noApplicationsYet: "No Applications Yet",
    noApplicationsYetDesc: "Developers haven't applied for this job yet.",
    reviewApplications: "Review applications submitted by developers.",
    stayUpdated: "Stay up to date with job updates and responses.",
    allCaughtUp: "You're all caught up. Check back later.",
    markAsRead: "Mark as Read",
    payDeveloperTitle: "Pay Developer",
    payDeveloperDescription: "Enter the M-Pesa number to send the STK push.",
    paymentSuccess: "STK push sent successfully.",
    paymentFailed: "Payment initiation failed.",
    paymentLoading: "Sending...",
    accept: "Accept",
    reject: "Reject",
    loadingApplicants: "Loading applicants...",
    jobApplicantsTitle: "Job Applicants",
    loginFailed: "Login failed. Please check your credentials.",
    registrationSuccess: "Registration successful! Redirecting to login...",
    registrationFailed: "Registration failed. Please try again.",
    confirmDelete: "Are you sure you want to delete this job listing?",
    deleteError: "Could not delete job. Please try again.",
    somethingWentWrong: "Something went wrong",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordSubtitle: "Enter your email to receive an OTP",
    sendingOtp: "Sending OTP...",
    sendOtp: "Send OTP",
    backToLogin: "Back to Login",
    passwordsDoNotMatch: "Passwords do not match.",
    passwordTooShort: "Password must be at least 6 characters long.",
    resetPasswordFailed: "Failed to reset password.",
    passwordResetSuccessful: "Password Reset Successful",
    passwordResetSuccessMessage: "Your password has been updated successfully.",
    redirectingToLogin: "Redirecting to login...",
    resetPasswordTitle: "Reset Password",
    resetPasswordSubtitle: "Enter your new password below.",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    resettingPassword: "Resetting Password...",
    invalidOtp: "Invalid or expired OTP",
    verifyOtpTitle: "Verify OTP",
    verifyOtpSubtitle: "Enter the OTP sent to",
    otpPlaceholder: "Enter 6-digit OTP",
    verifyingOtp: "Verifying...",
    browseJobsSubtitle:
      "Discover freelance opportunities that match your skills.",
    minimumBudget: "Minimum Budget",
    requiredSkill: "Required Skill",
    adjustFilters: "Try adjusting your search filters.",
    viewDetails: "View Details",
    editJob: "Edit Job",
    jobUpdatedSuccessfully: "Job updated successfully!",
    jobUpdateFailed: "Failed to update job.",
    updateJob: "Update Job",
  },
  sw: {
    // Swahili
    login: "Ingia",
    register: "Jisajili",
    email: "Barua pepe",
    password: "Nenosiri",
    username: "Jina la mtumiaji",
    role: "Jukumu",
    jobs: "Kazi",
    browseJobs: "Tazama Kazi",
    createJob: "Tengeneza Kazi",
    myJobs: "Kazi Zangu",
    jobTitle: "Jina la Kazi",
    description: "Maelezo",
    budget: "Bajeti",
    skills: "Ujuzi",
    dashboard: "Dashibodi",
    profile: "Profaili",
    notifications: "Arifa",
    save: "Hifadhi",
    cancel: "Ghairi",
    delete: "Futa",
    edit: "Hariri",
    loading: "Inapakia...",
    noData: "Hakuna data",
    search: "Tafuta",
    filter: "Chuja",
    applications: "Maombi",
    apply: "Omba",
    coverLetter: "Barua ya maombi",
    applicants: "Waombaji",
    status: "Hali",
    pending: "Inasubiri",
    accepted: "Imekubaliwa",
    rejected: "Imekataliwa",
    clientDashboardSubtitle:
      "Simamia orodha za kazi zako na fuatilia maombi ya wasanidi programu.",
    dashboardStatistics: "Takwimu za Dashibodi",
    quickActions: "Vitendo vya Haraka",
    loadingDashboard: "Inapakia dashibodi...",
    createJobDesc: "Chapisha orodha mpya ya kazi.",
    myJobsDesc: "Angalia na simamia kazi ulizochapisha.",
    profileDesc: "Sasisha maelezo ya akaunti yako.",
    notificationsDesc: "Angalia arifa zako zote za hivi karibuni.",
    welcomeBack: "Karibu Tena",
    welcomeSubtitle: "Ingiza taarifa zako ili ufikie akaunti yako",
    emailAddress: "Anwani ya barua pepe",
    forgotPassword: "Umesahau nywila?",
    dontHaveAccount: "Huna akaunti?",
    signIn: "Ingia",
    signUp: "Jisajili",
    getStarted: "Anza",
    createAccountSubtitle: "Unda akaunti ili ujiunge na jumuiya ya SkillSync",
    alreadyHaveAccount: "Tayari una akaunti?",
    createNewJob: "Tengeneza Kazi Mpya",
    jobDescription: "Maelezo ya Kazi",
    createJobButton: "Tengeneza Kazi",
    jobCreatedSuccessfully: "Kazi imeundwa kwa mafanikio!",
    failedToCreateJob: "Imeshindwa kuunda kazi",
    backToJobs: "Rudi kwenye Kazi",
    client: "Mteja",
    posted: "Iliyowekwa",
    requiredSkills: "Ujuzi unaohitajika",
    applyForThisJob: "Omba kazi hii",
    coverLetterPlaceholder:
      "Eleza kwa nini wewe ni msanidi anayefaa kwa mradi huu...",
    applyNow: "Omba Sasa",
    submitting: "Inatuma...",
    loadingJob: "Inapakia kazi...",
    pleaseWriteCoverLetter: "Tafadhali andika barua yako ya maombi.",
    applicationSubmitted: "Maombi yametumwa kwa mafanikio.",
    applicationFailed: "Uwasilishaji wa maombi umeshindikana.",
    myPostedJobs: "Kazi Zangu Zilizochapishwa",
    newest: "Mpya Zaidi",
    highestBudget: "Bajeti ya Juu",
    lowestBudget: "Bajeti ya Chini",
    postNewJob: "Chapisha Kazi Mpya",
    loadingYourJobs: "Inapakia kazi zako...",
    noJobsPosted: "Hujachapisha kazi yoyote bado.",
    viewApplicants: "Angalia Waombaji",
    paymentPendingApproval: "Malipo yanasubiri idhini",
    developerPaid: "Msanidi amelipwa",
    payDeveloper: "Lipa Msanidi",
    sendSTKPush: "Tuma STK Push",
    enterMpesaNumber: "Ingiza nambari ya M-Pesa ili kutuma STK push.",
    cancelButton: "Ghairi",
    noApplicationsYet: "Hakuna Maombi Yaliyowekwa",
    noApplicationsYetDesc: "Wasanidi programu hawajaomba kazi hii bado.",
    reviewApplications: "Kagua maombi yaliyoletwa na wasanidi programu.",
    stayUpdated: "Baki upate taarifa za masasisho ya kazi na majibu.",
    allCaughtUp: "Umeshaandaliwa. Rudia baadaye.",
    markAsRead: "Weka Iliyosomwa",
    payDeveloperTitle: "Lipa Msanidi",
    payDeveloperDescription: "Ingiza nambari ya M-Pesa ili kutuma STK push.",
    paymentSuccess: "STK push imetumwa kwa mafanikio.",
    paymentFailed: "Uanzishaji wa malipo umeshindikana.",
    paymentLoading: "Inatuma...",
    accept: "Kubali",
    reject: "Kataa",
    loadingApplicants: "Inapakia waombaji...",
    jobApplicantsTitle: "Waombaji wa Kazi",
    loginFailed: "Ingia imeshindikana. Tafadhali angalia taarifa zako.",
    registrationSuccess: "Uandikishaji umefanikiwa! Inarudia kwenye ingia...",
    registrationFailed: "Uandikishaji umeshindikana. Tafadhali jaribu tena.",
    confirmDelete: "Je, una uhakika unataka kufuta tangazo hili la kazi?",
    deleteError: "Haikuweza kufuta kazi. Tafadhali jaribu tena.",
    somethingWentWrong: "Kitu kilienda vibaya",
    forgotPasswordTitle: "Umesahau Nywila",
    forgotPasswordSubtitle: "Ingiza barua pepe yako ili upokee OTP",
    sendingOtp: "Inatuma OTP...",
    sendOtp: "Tuma OTP",
    backToLogin: "Rudi Kuingia",
    passwordsDoNotMatch: "Nywila hazilingani.",
    passwordTooShort: "Nywila lazima iwe angalau herufi 6.",
    resetPasswordFailed: "Imeshindwa kuweka upya nywila.",
    passwordResetSuccessful: "Kuweka upya nywila kumefanikiwa",
    passwordResetSuccessMessage: "Nywila yako imeboreshwa kwa mafanikio.",
    redirectingToLogin: "Inarudia kwenye ingia...",
    resetPasswordTitle: "Weka upya Nywila",
    resetPasswordSubtitle: "Ingiza nywila yako mpya hapa chini.",
    newPassword: "Nywila Mpya",
    confirmNewPassword: "Thibitisha Nywila Mpya",
    resettingPassword: "Inarekebisha nywila...",
    invalidOtp: "OTP batili au imeisha muda",
    verifyOtpTitle: "Thibitisha OTP",
    verifyOtpSubtitle: "Ingiza OTP iliyotumwa kwa",
    otpPlaceholder: "Ingiza OTP ya tarakimu 6",
    verifyingOtp: "Inathibitisha...",
    browseJobsSubtitle: "Gundua fursa za kazi zinazolingana na ujuzi wako.",
    minimumBudget: "Bajeti ya chini",
    requiredSkill: "Ujuzi unaohitajika",
    adjustFilters: "Jaribu kurekebisha vichungi vyako vya utafutaji.",
    viewDetails: "Angalia Maelezo",
    editJob: "Hariri Kazi",
    jobUpdatedSuccessfully: "Kazi imeboreshwa kwa mafanikio!",
    jobUpdateFailed: "Imeshindwa kusasisha kazi.",
    updateJob: "Sasisha Kazi",
  },
  fr: {
    // French
    login: "Connexion",
    register: "S'inscrire",
    email: "E-mail",
    password: "Mot de passe",
    username: "Nom d'utilisateur",
    role: "Rôle",
    jobs: "Emplois",
    browseJobs: "Parcourir les emplois",
    createJob: "Créer un emploi",
    myJobs: "Mes emplois",
    jobTitle: "Titre du poste",
    description: "Description",
    budget: "Budget",
    skills: "Compétences",
    dashboard: "Tableau de bord",
    profile: "Profil",
    notifications: "Notifications",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    loading: "Chargement...",
    noData: "Aucune donnée",
    search: "Rechercher",
    filter: "Filtrer",
    applications: "Candidatures",
    apply: "Postuler",
    coverLetter: "Lettre de motivation",
    applicants: "Candidats",
    status: "Statut",
    pending: "En attente",
    accepted: "Accepté",
    rejected: "Rejeté",
    clientDashboardSubtitle:
      "Gérez vos offres d'emploi et suivez les candidatures des développeurs.",
    dashboardStatistics: "Statistiques du tableau de bord",
    quickActions: "Actions rapides",
    loadingDashboard: "Chargement du tableau de bord...",
    createJobDesc: "Publier une nouvelle offre d'emploi.",
    myJobsDesc: "Consultez et gérez vos offres publiées.",
    profileDesc: "Mettez à jour les détails de votre compte.",
    notificationsDesc: "Consultez toutes vos dernières notifications.",
    welcomeBack: "Bon retour",
    welcomeSubtitle: "Saisissez vos identifiants pour accéder à votre compte",
    emailAddress: "Adresse e-mail",
    forgotPassword: "Mot de passe oublié ?",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    getStarted: "Commencer",
    createAccountSubtitle:
      "Créez un compte pour rejoindre la communauté SkillSync",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    createNewJob: "Créer un nouvel emploi",
    jobDescription: "Description du poste",
    createJobButton: "Créer un emploi",
    jobCreatedSuccessfully: "Emploi créé avec succès !",
    failedToCreateJob: "Échec de la création de l'emploi",
    backToJobs: "Retour aux emplois",
    client: "Client",
    posted: "Publié",
    requiredSkills: "Compétences requises",
    applyForThisJob: "Postuler à cet emploi",
    coverLetterPlaceholder:
      "Expliquez pourquoi vous êtes le bon développeur pour ce projet...",
    applyNow: "Postuler maintenant",
    submitting: "Soumission...",
    loadingJob: "Chargement du poste...",
    pleaseWriteCoverLetter: "Veuillez rédiger votre lettre de motivation.",
    applicationSubmitted: "Candidature soumise avec succès.",
    applicationFailed: "La soumission de la candidature a échoué.",
    myPostedJobs: "Mes offres publiées",
    newest: "Le plus récent",
    highestBudget: "Budget le plus élevé",
    lowestBudget: "Budget le plus bas",
    postNewJob: "Publier un nouvel emploi",
    loadingYourJobs: "Chargement de vos emplois...",
    noJobsPosted: "Vous n'avez encore publié aucun emploi.",
    viewApplicants: "Voir les candidats",
    paymentPendingApproval: "Paiement en attente d'approbation",
    developerPaid: "Développeur payé",
    payDeveloper: "Payer le développeur",
    sendSTKPush: "Envoyer l'STK Push",
    enterMpesaNumber: "Entrez le numéro M-Pesa pour envoyer l'STK push.",
    cancelButton: "Annuler",
    noApplicationsYet: "Aucune candidature pour l'instant",
    noApplicationsYetDesc:
      "Les développeurs n'ont pas encore postulé à cet emploi.",
    reviewApplications:
      "Passez en revue les candidatures soumises par les développeurs.",
    stayUpdated:
      "Restez informé des mises à jour et des réponses concernant les emplois.",
    allCaughtUp: "Vous êtes à jour. Revenez plus tard.",
    markAsRead: "Marquer comme lu",
    payDeveloperTitle: "Payer le développeur",
    payDeveloperDescription: "Entrez le numéro M-Pesa pour envoyer l'STK push.",
    paymentSuccess: "L'STK push a été envoyé avec succès.",
    paymentFailed: "L'initiation du paiement a échoué.",
    paymentLoading: "Envoi...",
    accept: "Accepter",
    reject: "Rejeter",
    loadingApplicants: "Chargement des candidats...",
    jobApplicantsTitle: "Candidats",
    loginFailed: "Échec de connexion. Veuillez vérifier vos identifiants.",
    registrationSuccess:
      "Inscription réussie ! Redirection vers la connexion...",
    registrationFailed: "L'inscription a échoué. Veuillez réessayer.",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cette offre d'emploi ?",
    deleteError: "Impossible de supprimer l'emploi. Veuillez réessayer.",
    somethingWentWrong: "Une erreur s'est produite",
    forgotPasswordTitle: "Mot de passe oublié",
    forgotPasswordSubtitle: "Entrez votre e-mail pour recevoir un OTP",
    sendingOtp: "Envoi de l'OTP...",
    sendOtp: "Envoyer l'OTP",
    backToLogin: "Retour à la connexion",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",
    passwordTooShort: "Le mot de passe doit contenir au moins 6 caractères.",
    resetPasswordFailed: "Échec de la réinitialisation du mot de passe.",
    passwordResetSuccessful: "Réinitialisation du mot de passe réussie",
    passwordResetSuccessMessage:
      "Votre mot de passe a été mis à jour avec succès.",
    redirectingToLogin: "Redirection vers la connexion...",
    resetPasswordTitle: "Réinitialiser le mot de passe",
    resetPasswordSubtitle: "Entrez votre nouveau mot de passe ci-dessous.",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    resettingPassword: "Réinitialisation du mot de passe...",
    invalidOtp: "OTP invalide ou expiré",
    verifyOtpTitle: "Vérifier l'OTP",
    verifyOtpSubtitle: "Entrez l'OTP envoyé à",
    otpPlaceholder: "Entrez un OTP à 6 chiffres",
    verifyingOtp: "Vérification...",
    browseJobsSubtitle:
      "Découvrez des opportunités freelance correspondant à vos compétences.",
    minimumBudget: "Budget minimum",
    requiredSkill: "Compétence requise",
    adjustFilters: "Essayez d'ajuster vos filtres de recherche.",
    viewDetails: "Voir les détails",
    editJob: "Modifier l'emploi",
    jobUpdatedSuccessfully: "Emploi mis à jour avec succès !",
    jobUpdateFailed: "Échec de la mise à jour de l'emploi.",
    updateJob: "Mettre à jour l'emploi",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
